### ISSUE TITLE
Port matrix exponential code from scipy

### ISSUE THREAD

**Issue by sritchie** [littleredcomputer/sicmutils#110]
The "Pade approximation" should knock this off for us: https://github.com/scipy/scipy/blob/v1.5.2/scipy/linalg/matfuncs.py#L210-L255

**Comment by littleredcomputer** [comment]
(Or we could generate the series :)

**Comment by sritchie** [comment]
Awesome idea @littleredcomputer ! I get it now, after working on #142  :)

**Comment by sritchie** [comment]
Okay, closing since we now have this in #142.
