### ISSUE TITLE
Multimethods for sub, add, div, expt need some attention re structures

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/sicmutils#15]
As it should be: (mul)
```
[sicmutils.env] > (* (up 'a 'b) 'c)
(up (* a c) (* b c))
[sicmutils.env] > (* 'a (up 'b 'c))
(up (* a b) (* a c))
```
Not quite as good (div)
```
(up (* a b) (* a c))
[sicmutils.env] > (/ (up 'a 'b) 'c)
(up (/ a c) (/ b c))
[sicmutils.env] > (/ 'a (up 'b 'c))

IllegalArgumentException No method in multimethod 'div' for dispatch value: [clojure.lang.Symbol :sicmutils.structure/up]  clojure.lang.MultiFn.getFn (MultiFn.java:156)
```
Could be better (add, expt)
```
[sicmutils.env] > (+ (up 'a 'b) 'c)

IllegalArgumentException No method in multimethod 'add' for dispatch value: [:sicmutils.structure/up clojure.lang.Symbol]  clojure.lang.MultiFn.getFn (MultiFn.java:156)
[sicmutils.env] > (+ 'a (up 'b 'c))
IllegalArgumentException No method in multimethod 'add' for dispatch value: [clojure.lang.Symbol :sicmutils.structure/up]  clojure.lang.MultiFn.getFn (MultiFn.java:156)

[sicmutils.env] > (expt (up 'a 'b) 'c)
IllegalArgumentException No method in multimethod 'expt' for dispatch value: [:sicmutils.structure/up clojure.lang.Symbol]  clojure.lang.MultiFn.getFn (MultiFn.java:156)

[sicmutils.env] > (expt 'a (up 'b 'c))

IllegalArgumentException No method in multimethod 'expt' for dispatch value: [clojure.lang.Symbol :sicmutils.structure/up]  clojure.lang.MultiFn.getFn (MultiFn.java:156)
```
sub gives two different messages
```
[sicmutils.env] > (- (up 'a 'b) 'c)

IllegalArgumentException No method in multimethod 'sub' for dispatch value: [:sicmutils.structure/up clojure.lang.Symbol]  clojure.lang.MultiFn.getFn (MultiFn.java:156)
[sicmutils.env] > (- 'a ('b 'c))

IllegalArgumentException No implementation of method: :nullity? of protocol: #'sicmutils.value/Value found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:554)
```

**Comment by alexgian** [comment]
Similarly for the unary functions, trig needs no be implemented

As it should be:
```
[sicmutils.env] > (- (up 'a 'b))
(up (* -1 a) (* -1 b))
```
needs implementation
```
[sicmutils.env] > (sin (up 'a 'b))

IllegalArgumentException No method in multimethod 'sin' for dispatch value: :sicmutils.structure/up  clojure.lang.MultiFn.getFn (MultiFn.java:156)
```

**Comment by alexgian** [comment]
I should add that MIT scmutils does not actually define these generic operations, so if you have any objections, I am happy if they are left out for now, although I think they *should* be defined since they are simply scalar operations on a vector, albeit a "structure".  Someone wanting to get a taster of structures as vectors would find it a whole lot more acceptable if they behaved predictably where one would expect them to do so.

In any case a user could simply
```
> (apply up (map (partial + 'c) (up 'a 'b)))  ==>  (up (+ c a) (+ c b))
```
So we are merely saving them the syntactic hassle.

**Comment by littleredcomputer** [comment]
I think we're scmutils-compatible here for the moment. My inclination is to leave it alone. (There's a tiny shortcut available, `(s/mapr #(+ % 'c) (down 1 2 3))` to get `(down (+ c 1) (+ c 2) (+ c 3))` (the advantage of mapr is you don't have to remember to wrap the structure back up after the mapping. Although it is recursive and will flood the operation down to all levels of the struct if it is deeper than a vector. Sometimes you want that, sometimes you don't; I should expose s/map as well). You can save one step in your second example by using `(mapv)` instead of `(vec (map))`. Or we could allow the arithmetic operations on things like you suggest. The downside of that is that adding a scalar to a vector might mean you are doing something wrong that you might like to know about rather than be surprised by a complicated expression somewhere down the line. So I lean toward letting the user write one of these snippets if that is what she wants.

**Comment by littleredcomputer** [comment]
Another trick from the undocumented realm:

```
(def u (up 1 2))
(s/same u (map #(+ % 'c) u))
```

**Comment by alexgian** [comment]
OK.
Although looking at structures.clj, I see that, for instance, add and sub *are* defined as elementwise operations.  Has this simply not been "pulled up" into the greater scheme of things?

**Comment by alexgian** [comment]
OK.
I'll close for now.

**Comment by alexgian** [comment]
I think a shimmed definition for map somewhere along these lines would be perfect:
```
(defn s/map [op struct] (sicmutils.structure/same struct (map op struct)))
```
Then the user would have both s/map and s/mapr to play with, nice, consistent and easily documentable...
Or you could call it "struct-map" or similar if you don't like "map", although I think "map" is perfect, it extends Clojure's map over sicmutils structures, just as one would expect.
