### ISSUE TITLE
Need to define "ref" as index for structures

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/sicmutils#16]
Even though it's a Clojure function, perhaps it can be generalised somehow - by arg type, perhaps? -, or shimmed in the manner of "partial".

Even though it's only referenced twice in SICM (fn p.17 and "Our Notation" p.494) it is used a lot in FDG.

**Comment by littleredcomputer** [comment]
Gulp. The definition of ref in scmutils is over 120 lines long. It does a lot of things (many of which we're not ready for, like reffing into power series.) 

Still, it's worth a try providing a shim.

**Comment by alexgian** [comment]
Just indexing into structures would be great for a start.
