### ISSUE TITLE
invert

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/sicmutils#22]
Could we have g/invert promoted into env.clj  please (as per scmutils, as ever)

**Comment by littleredcomputer** [comment]
Will do  (in the meantime, note that (/ x) maps to (invert x)... when there's just one argument.

**Comment by alexgian** [comment]
> note that (/ x) maps to (invert x)... when there's just one argument.

Hadn't noticed.... Cute (and Correct) - like ÷ in APL, % in J.
