### ISSUE TITLE
GPL v3 is incompatible with EPL

### ISSUE THREAD

**Issue by whilo** [littleredcomputer/sicmutils#31]
Thanks for your great work. I think it might be useful in implementing automatic differentiation for neural networks. I have also started to explore examples from FDG. It has popped up a few times already, e.g. https://ujihisa.wordpress.com/2013/12/11/releasing-clojure-applications-with-gplv3/. Could you consider relicencing in compatible fashion? Since scmutils is under GPL appearingly, you could add a clause that excludes all dependencies. I am not a legal expert though (maybe the FSF can help).

**Comment by littleredcomputer** [comment]
Thank you for your kind remarks!

When I chose the license I was unaware of some of the friction around GPLv3. I think the easiest thing to do would be just to change the license to GPLv2. Apparently I can do this, so I will.

**Comment by whilo** [comment]
It is not just v3 unfortunately. GPL and EPL are incompatible due to the FSF. Maybe you (or we) can get  allowance to relicence under EPL (it is like LGPL in a sense). It is a bit annoying that Clojure is not GPL compatible.

**Comment by littleredcomputer** [comment]
As you point out, it is [more complicated](https://groups.google.com/forum/#!topic/clojure/TfPK-ljC46I) than I thought. Although, if you use the code as source instead of in a jar, perhaps the issue is less thorny? I could ask the original authors of scmutils if they would object to my relicensing the whole thing as MIT (that's where the original work comes from anyway. My choice of GPL was only to respect the choice the authors of the original work made). Or, adding an additional paragraph to the license as suggested in the linked thread might be the path of least resistance.

**Comment by whilo** [comment]
Hey. Have you had any success in reaching Prof. Sussman and/or his collaborators? I am working on autodiff approaches for https://probprog.github.io/anglican/ now and it would be really cool to have access to CAS like features. I am also looking at clojuratica, but this would be more of a REPL helper, not a library to depend on.

**Comment by littleredcomputer** [comment]
Sorry: this fell off my radar. I'm on vacation this week, but will take the matter up with the maintainers next week and report back here.

**Comment by whilo** [comment]
Ok, great! Thanks a lot, I think your work has really great potential for scientific computing in Clojure!

**Comment by littleredcomputer** [comment]
I'm in contact with GJS, and he's busy this week, so he invited me to talk to him next week.

**Comment by littleredcomputer** [comment]
Finally spoke to GJS. He is quite firm in the choice of GPL for the source work, and therefore I think it's clear that the license for this code should be consistent with that. Consequently the license here will remain GPL. Thank you for your patience.

**Comment by whilo** [comment]
I already assumed this was the case. Thank you for trying to address the issue.
