### ISSUE TITLE
Add cljdoc build

### ISSUE THREAD

**Issue by sritchie** [littleredcomputer/sicmutils#91]
CLJDoc has a build already for our API Docs: https://cljdoc.org/d/net.littleredcomputer/sicmutils/0.12.1

I pushed a change that will let the site find the git repo, so the readme should show up next time we make a release. It would be nice to add a loose table of contents and some documentation that we can begin to flesh out. Here's the guide: https://github.com/cljdoc/cljdoc

Another option is https://github.com/oakes/Dynadoc. This lets you embed actual runnable examples in the documentation. This could be incredible, now that we're fully cljs compatible.

**Comment by littleredcomputer** [comment]
This is cool. Scmutils (the original) has nothing close to this. Exciting.

**Comment by sritchie** [comment]
Boom, covered in #170 .
