### ISSUE TITLE
No `div` impl between numbers and polynomials

### ISSUE THREAD

**Issue by sritchie** [littleredcomputer/sicmutils#93]
The following code, in a namespace with the proper imports like `sicmutils.simplify-test`:

```clojure
(sicmutils.simplify/hermetic-simplify-fixture
 (fn []
   (g/simplify
    (g/mul 0.5
           (g/div 1 (g/mul 2 'x))))))
```

Throws:

```
Execution error (Error) at (<cljs repl>:1).
No method in multimethod 'sicmutils.generic/div' for dispatch value: [#object[Number] :sicmutils.polynomial/polynomial]
```

Everything works if we use `(/ 1 2)` to generate a ratio. Do we want to handle a floating point number here? 

Well, of course we do. I guess I would expect here that maybe the simplifier would do nothing, and return `(/ 0.5 (* 2 x))`.

**Comment by littleredcomputer** [comment]
That would be my expectation too. Does 0.5 register as exact now?

**Comment by sritchie** [comment]
looks like it doesn't. I can try and dig in to where this multiplication is happening, too. possibly notable is that it times out, and only succeeds (with that error) when I wrap it with `hermetic-simplify-fixture`. More demons to chase!

**Comment by littleredcomputer** [comment]
If memory serves the 0.5 should have been converted to a symbol by the
analyzer, so that it would form a rational function when divided by the
polynomial in the denominator. Then the backsubstition pass would replace
the symbol with 0.5 after we're done grinding through the simplification,
so we definitely don't need an implementation of the div.

**Comment by sritchie** [comment]
Okay, I fixed this by adding an explicit implementation of `invert` for polynomials in the `rational-function` namespace:

```clojure
(defmethod g/invert [::p/polynomial] [^Polynomial p]
  (make (p/make-constant (.-arity p) 1) p))
```

**Comment by sritchie** [comment]
Adding this to #169 .
